FROM ubuntu:20.04

ADD src/submodules/binrec binrec 

WORKDIR binrec/


RUN dpkg --add-architecture i386
RUN apt-get update && \
    apt-get -y install --no-install-recommends apt-utils && \
    apt-get -y install sudo 
RUN ./get_just.sh
RUN just install-binrec